nginx:
    image: nginx:1.9
    ports:
        - "80:80"
    links:
        - php
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
        - ./nginx/html:/usr/share/nginx/html:ro
        - ./nginx/log:/var/log/nginx:rw

php:
    image: php:5.6-fpm
    ports:
      - "9000:9000"
    volumes:
        - ./nginx/html:/usr/share/nginx/html:ro
